### PR TITLE
Remove css from bower.json main

### PR DESCRIPTION
**Pull request by jmmendivil**
scroll-kit.css doesn't exists

### CODE REVIEW

**Comment by pateketrueke** [comment]
Seems legit, thanks!

**Comment by pateketrueke** [comment]
Closing by now, I need to patch this manually.

**Comment by jmmendivil** [comment]
Can you elaborate?
automatic bower include fails because of this

**Comment by pateketrueke** [comment]
Manually merged, `v0.3.2` released. 🍺

**Pull request closed without merging**
